import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router";
import {
  HistoryIcon,
  ArrowLeftIcon,
  SparklesIcon,
  ClockIcon,
  MessageSquareIcon,
  Loader2Icon,
  DownloadIcon,
} from "lucide-react";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer,
} from "recharts";
import Navbar from "../components/Navbar";
import SessionHistoryCard from "../components/SessionHistoryCard";
import AIFeedbackCard from "../components/AIFeedbackCard";
import { useAIPractice } from "../hooks/useAIPractice";
import { motion } from "framer-motion";

function AIPracticeHistoryPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const {
    history, historyMeta, currentSession,
    loadHistory, loadSession,
  } = useAIPractice();

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        if (id) {
          await loadSession(id);
        } else {
          await loadHistory(1);
        }
      } catch (err) {
        console.error("Failed to load data:", err);
      }
      setLoading(false);
    };
    fetchData();
  }, [id]);

  const formatDuration = (seconds) => {
    if (!seconds) return "—";
    const mins = Math.round(seconds / 60);
    return `${mins} min`;
  };

  const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleDateString("en-US", {
      weekday: "long",
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  const handleDownloadReport = (feedback, sessionMeta) => {
    const lines = [
      "TALENTIQ — INTERVIEW REPORT",
      "════════════════════════════════",
      `Date:       ${new Date().toLocaleDateString()}`,
      `Topic:      ${sessionMeta?.topic || "Resume Interview"}`,
      `Type:       ${sessionMeta?.interviewType || "—"}`,
      `Difficulty: ${sessionMeta?.difficulty || "—"}`,
      `Duration:   ${Math.round((sessionMeta?.totalDuration || 0) / 60)} min`,
      `Questions:  ${sessionMeta?.questionCount || 0}`,
      "",
      "── SCORES ──────────────────────",
      `Overall Score:    ${feedback?.overallScore || 0}/10`,
      `Communication:    ${feedback?.communication || 0}/10`,
      `Technical Depth:  ${feedback?.technicalDepth || 0}/10`,
      `Problem Solving:  ${feedback?.problemSolving || 0}/10`,
      `Confidence:       ${feedback?.confidence || 0}/10`,
      "",
      "── STRENGTHS ───────────────────",
      ...(feedback?.strengths?.map((s) => `• ${s}`) || ["—"]),
      "",
      "── IMPROVEMENTS ────────────────",
      ...(feedback?.improvements?.map((i) => `• ${i}`) || ["—"]),
      "",
      "── SUMMARY ─────────────────────",
      feedback?.summary || "—",
      "",
      "── QUESTION BREAKDOWN ──────────",
      ...(feedback?.questionBreakdown?.flatMap((q, i) => [
        `Q${i + 1}: ${q.question}`,
        `     Score: ${q.score}/10 — ${q.comment}`,
        "",
      ]) || ["—"]),
      "════════════════════════════════",
      "Generated by TalentIQ",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TalentIQ_Report_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (id && currentSession) {
    const session = currentSession;
    return (
      <div className="min-h-screen bg-[var(--dark-bg)]">
        <Navbar />
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-4xl mx-auto px-6 py-12"
        >
          <div className="flex items-center gap-4 mb-8">
            <button
              className="btn-ghost-dark text-xs gap-1 px-3 py-1.5 border border-[var(--dark-border)]"
              onClick={() => navigate("/ai-practice/history")}
            >
              <ArrowLeftIcon className="size-3" />
              Back to History
            </button>
            <button
              className="btn-outline-dark text-xs gap-1.5 px-3 py-1.5"
              onClick={() =>
                handleDownloadReport(session.feedback, {
                  topic: session.topic,
                  difficulty: session.difficulty,
                  questionCount: session.questionCount,
                  totalDuration: session.totalDuration,
                })
              }
            >
              <DownloadIcon className="size-3" />
              Download Report
            </button>
          </div>

          <div className="flex flex-wrap items-center gap-3 mb-4">
            <h1 className="text-3xl font-black text-[var(--dark-text)]">
              {session.mode === "topic"
                ? session.topic || "Topic Interview"
                : "Resume Interview"}
            </h1>
            <span
              className={`text-[10px] uppercase tracking-widest font-bold px-2.5 py-1 rounded-full border ${
                session.mode === "topic" 
                  ? "border-[var(--color-info-border)] text-[var(--color-info)] bg-[var(--color-info-bg)]" 
                  : "border-[var(--color-purple-border)] text-[var(--color-purple)] bg-[var(--color-purple-bg)]"
              }`}
            >
              {session.mode === "topic" ? "Topic" : "Resume"}
            </span>
            {session.difficulty && (
              <span
                className={`text-[10px] uppercase tracking-widest font-bold px-2.5 py-1 rounded-full border ${
                  session.difficulty === "Easy"
                    ? "border-[var(--color-success-border)] text-[var(--color-success)] bg-[var(--color-success-bg)]"
                    : session.difficulty === "Medium"
                    ? "border-[var(--color-warning-border)] text-[var(--color-warning)] bg-[var(--color-warning-bg)]"
                    : "border-[var(--color-danger-border)] text-[var(--color-danger)] bg-[var(--color-danger-bg)]"
                }`}
              >
                {session.difficulty}
              </span>
            )}
          </div>

          <div className="flex flex-wrap gap-4 text-sm text-[var(--dark-text-secondary)] mb-10 bg-[var(--dark-card)] px-4 py-3 rounded-xl border border-[var(--dark-border)] w-fit">
            <div className="flex items-center gap-2">
              <ClockIcon className="size-4 text-[var(--dark-text-tertiary)]" />
              {formatDuration(session.totalDuration)}
            </div>
            <div className="w-px h-4 bg-[var(--dark-border)]"></div>
            <div className="flex items-center gap-2">
              <MessageSquareIcon className="size-4 text-[var(--dark-text-tertiary)]" />
              {session.questionCount || 0} questions
            </div>
            <div className="w-px h-4 bg-[var(--dark-border)]"></div>
            <div>{formatDate(session.createdAt)}</div>
          </div>

          {session.feedback && (
            <div className="mb-10">
              <AIFeedbackCard
                variant="practice"
                feedback={session.feedback}
                sessionMeta={{
                  mode: session.mode,
                  topic: session.topic,
                  difficulty: session.difficulty,
                  questionCount: session.questionCount,
                  totalDuration: session.totalDuration,
                }}
              />
            </div>
          )}

          <div className="card-dark p-6 md:p-8">
            <h2 className="font-bold text-lg mb-6 flex items-center gap-2 text-[var(--dark-text)] border-b border-[var(--dark-border)] pb-4">
              <MessageSquareIcon className="size-5 text-[var(--dark-accent)]" />
              Conversation Transcript
            </h2>
            <div className="space-y-6">
              {session.messages?.map((msg, i) => (
                <div
                  key={i}
                  className={`flex ${
                    msg.role === "ai" ? "justify-start" : "justify-end"
                  }`}
                >
                  <div
                    className={`flex gap-3 max-w-[85%] md:max-w-[75%] ${
                      msg.role === "ai" ? "flex-row" : "flex-row-reverse"
                    }`}
                  >
                    <div
                      className={`flex-shrink-0 size-8 rounded-full flex items-center justify-center border ${
                        msg.role === "ai"
                          ? "bg-[var(--dark-elevated)] border-[var(--dark-border)]"
                          : "bg-[var(--dark-accent-bg)] border-[var(--dark-accent-border)]"
                      }`}
                    >
                      {msg.role === "ai" ? (
                        <SparklesIcon className="size-4 text-[var(--dark-accent)]" />
                      ) : (
                        <span className="text-[10px] font-bold text-[var(--dark-accent)] uppercase">
                          You
                        </span>
                      )}
                    </div>
                    <div>
                      <div className={`text-[10px] font-bold mb-1 uppercase tracking-wider ${msg.role === "ai" ? "text-[var(--dark-text-secondary)]" : "text-[var(--dark-text-secondary)] text-right"}`}>
                        {msg.role === "ai" ? "Interviewer" : "You"}
                      </div>
                      <div
                        className={`rounded-2xl px-5 py-4 text-sm leading-relaxed border ${
                          msg.role === "ai"
                            ? "bg-[var(--dark-card)] text-[var(--dark-text)] border-[var(--dark-border)] rounded-tl-sm"
                            : "bg-[var(--dark-accent)] text-white border-[var(--dark-accent)] rounded-tr-sm font-medium"
                        }`}
                      >
                        {msg.content}
                      </div>
                      {msg.timeTaken > 0 && (
                        <div className={`text-[10px] text-[var(--dark-text-tertiary)] mt-1.5 font-semibold ${msg.role === "ai" ? "" : "text-right"}`}>
                          Answered in {msg.timeTaken}s
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    );
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 10 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  return (
    <div className="min-h-screen bg-[var(--dark-bg)]">
      <Navbar />
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-5xl mx-auto px-6 py-12"
      >
        <div className="flex items-center gap-4 mb-10">
          <div className="size-12 rounded-xl bg-[var(--dark-elevated)] border border-[var(--dark-border)] flex items-center justify-center shadow-lg">
            <HistoryIcon className="size-6 text-[var(--dark-accent)]" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-[var(--dark-text)]">Practice History</h1>
            <p className="text-sm text-[var(--dark-text-secondary)] mt-1">
              Review your past AI practice interview sessions
            </p>
          </div>
        </div>

        {!loading && history.length >= 2 && (
          <div className="card-dark p-6 mb-8 border border-[var(--dark-border)]">
            <h2 className="font-bold text-xs uppercase tracking-wider text-[var(--dark-text-secondary)] mb-6 flex items-center gap-2">
              <SparklesIcon className="size-4 text-[var(--dark-accent)]" /> Score Trend
            </h2>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart
                data={[...history].reverse().map((s, i) => ({
                  name: `Int #${i + 1}`,
                  score: s.feedback?.overallScore || 0,
                  topic: s.topic || "Resume",
                }))}
                margin={{ left: -20, bottom: 5, top: 10, right: 10 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                <XAxis dataKey="name" tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} dy={10} />
                <YAxis domain={[0, 10]} tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} tickCount={6} />
                <Tooltip
                  formatter={(val) => [`${val}/10`, "Score"]}
                  labelFormatter={(label, payload) =>
                    payload?.[0]?.payload?.topic || label
                  }
                  contentStyle={{ backgroundColor: "#ffffff", borderColor: "#e2e8f0", borderRadius: "8px", color: "#0f172a", fontSize: "12px" }}
                  itemStyle={{ color: "#0a66c2", fontWeight: "bold" }}
                />
                <Line
                  type="monotone"
                  dataKey="score"
                  stroke="#0a66c2"
                  strokeWidth={3}
                  dot={{ fill: "#ffffff", stroke: "#0a66c2", strokeWidth: 2, r: 4 }}
                  activeDot={{ r: 6, fill: "#0a66c2", stroke: "#ffffff", strokeWidth: 2 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        )}

        {!loading && history.length >= 1 && (() => {
          const topicStats = history.reduce((acc, session) => {
            const key = session.topic || "Resume";
            if (!acc[key]) acc[key] = { topic: key, total: 0, count: 0 };
            acc[key].total += session.feedback?.overallScore || 0;
            acc[key].count += 1;
            return acc;
          }, {});
          const topicArray = Object.values(topicStats)
            .map((t) => ({ ...t, avg: Math.round((t.total / t.count) * 10) / 10 }))
            .sort((a, b) => b.avg - a.avg);

          return (
            <div className="card-dark p-6 mb-10 border border-[var(--dark-border)]">
              <h2 className="font-bold text-xs uppercase tracking-wider text-[var(--dark-text-secondary)] mb-6 flex items-center gap-2">
                <SparklesIcon className="size-4 text-[var(--dark-accent)]" /> Performance by Topic
              </h2>
              <div className="space-y-4">
                {topicArray.map((t) => (
                  <div key={t.topic} className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                    <span className="text-sm w-full sm:w-40 truncate font-semibold text-[var(--dark-text)]">{t.topic}</span>
                    <div className="w-full h-2 bg-[var(--dark-bg)] rounded-full overflow-hidden flex-1 border border-[var(--dark-border)]">
                      <motion.div
                        className={`h-full rounded-full ${t.avg >= 7 ? "bg-[var(--color-success)]" : t.avg >= 4 ? "bg-[var(--color-warning)]" : "bg-[var(--color-danger)]"}`}
                        initial={{ width: 0 }}
                        animate={{ width: `${(t.avg / 10) * 100}%` }}
                        transition={{ duration: 1 }}
                      />
                    </div>
                    <div className="flex items-center gap-3 w-20 justify-between shrink-0">
                      <span className="text-sm font-mono font-bold text-[var(--dark-text)]">
                        {t.avg}<span className="text-[var(--dark-text-secondary)] text-xs font-normal">/10</span>
                      </span>
                      <span className="text-xs text-[var(--dark-text-tertiary)] font-bold">
                        {t.count}x
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })()}

        {loading ? (
          <div className="space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="card-dark p-6 border border-[var(--dark-border)] animate-pulse flex items-center justify-between">
                <div className="w-2/3 h-5 bg-[var(--dark-border)] rounded"></div>
                <div className="w-16 h-8 bg-[var(--dark-border)] rounded"></div>
              </div>
            ))}
          </div>
        ) : history.length === 0 ? (
          <div className="text-center py-24 bg-[var(--dark-card)] border border-[var(--dark-border)] rounded-2xl">
            <div className="size-20 rounded-full bg-[var(--dark-elevated)] border border-[var(--dark-border)] flex items-center justify-center mx-auto mb-6 shadow-inner">
              <SparklesIcon className="size-10 text-[var(--dark-text-tertiary)]" />
            </div>
            <h2 className="text-xl font-bold text-[var(--dark-text)] mb-2">
              No practice sessions yet
            </h2>
            <p className="text-[var(--dark-text-secondary)] mb-8 max-w-sm mx-auto">
              Start your first AI-powered practice interview and receive comprehensive feedback!
            </p>
            <button
              className="btn-green px-8"
              onClick={() => navigate("/ai-practice")}
            >
              Start Practicing Now
            </button>
          </div>
        ) : (
          <>
            <motion.div 
              variants={containerVariants}
              initial="hidden"
              animate="show"
              className="flex flex-col gap-3"
            >
              {history.map((session) => (
                <motion.div variants={itemVariants} key={session._id}>
                  <SessionHistoryCard
                    session={session}
                    onClick={() => navigate(`/ai-practice/history/${session._id}`)}
                  />
                </motion.div>
              ))}
            </motion.div>

            {historyMeta.totalPages > 1 && (
              <div className="flex justify-center mt-10 gap-2">
                {[...Array(historyMeta.totalPages)].map((_, i) => (
                  <button
                    key={i}
                    className={`size-8 rounded-lg text-sm font-semibold transition-colors flex items-center justify-center border ${
                      historyMeta.page === i + 1 
                        ? "bg-[var(--dark-accent-bg)] text-[var(--dark-accent)] border-[var(--dark-accent-border)]" 
                        : "bg-[var(--dark-card)] text-[var(--dark-text-secondary)] border-[var(--dark-border)] hover:text-[var(--dark-text)] hover:border-[var(--dark-text-tertiary)]"
                    }`}
                    onClick={() => loadHistory(i + 1)}
                  >
                    {i + 1}
                  </button>
                ))}
              </div>
            )}
          </>
        )}
      </motion.div>
    </div>
  );
}

export default AIPracticeHistoryPage;
