import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router";
import {
  HistoryIcon,
  ArrowLeftIcon,
  SparklesIcon,
  ClockIcon,
  MessageSquareIcon,
  Loader2Icon,
  DownloadIcon,
} from "lucide-react";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer,
} from "recharts";
import Navbar from "../components/Navbar";
import SessionHistoryCard from "../components/SessionHistoryCard";
import AIFeedbackCard from "../components/AIFeedbackCard";
import { useAIPractice } from "../hooks/useAIPractice";

function AIPracticeHistoryPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const {
    history, historyMeta, currentSession,
    loadHistory, loadSession,
  } = useAIPractice();

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        if (id) {
          await loadSession(id);
        } else {
          await loadHistory(1);
        }
      } catch (err) {
        console.error("Failed to load data:", err);
      }
      setLoading(false);
    };
    fetchData();
  }, [id]);

  const formatDuration = (seconds) => {
    if (!seconds) return "—";
    const mins = Math.round(seconds / 60);
    return `${mins} min`;
  };

  const formatDate = (dateStr) => {
    return new Date(dateStr).toLocaleDateString("en-US", {
      weekday: "long",
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  // ─── Download report helper ──────
  const handleDownloadReport = (feedback, sessionMeta) => {
    const lines = [
      "TALENTIQ — INTERVIEW REPORT",
      "════════════════════════════════",
      `Date:       ${new Date().toLocaleDateString()}`,
      `Topic:      ${sessionMeta?.topic || "Resume Interview"}`,
      `Type:       ${sessionMeta?.interviewType || "—"}`,
      `Difficulty: ${sessionMeta?.difficulty || "—"}`,
      `Duration:   ${Math.round((sessionMeta?.totalDuration || 0) / 60)} min`,
      `Questions:  ${sessionMeta?.questionCount || 0}`,
      "",
      "── SCORES ──────────────────────",
      `Overall Score:    ${feedback?.overallScore || 0}/10`,
      `Communication:    ${feedback?.communication || 0}/10`,
      `Technical Depth:  ${feedback?.technicalDepth || 0}/10`,
      `Problem Solving:  ${feedback?.problemSolving || 0}/10`,
      `Confidence:       ${feedback?.confidence || 0}/10`,
      "",
      "── STRENGTHS ───────────────────",
      ...(feedback?.strengths?.map((s) => `• ${s}`) || ["—"]),
      "",
      "── IMPROVEMENTS ────────────────",
      ...(feedback?.improvements?.map((i) => `• ${i}`) || ["—"]),
      "",
      "── SUMMARY ─────────────────────",
      feedback?.summary || "—",
      "",
      "── QUESTION BREAKDOWN ──────────",
      ...(feedback?.questionBreakdown?.flatMap((q, i) => [
        `Q${i + 1}: ${q.question}`,
        `     Score: ${q.score}/10 — ${q.comment}`,
        "",
      ]) || ["—"]),
      "════════════════════════════════",
      "Generated by TalentIQ",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TalentIQ_Report_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ═══════════════════════════════════════════════════════════════
  // VIEW 2: Session Detail
  // ═══════════════════════════════════════════════════════════════
  if (id && currentSession) {
    const session = currentSession;
    return (
      <div className="min-h-screen bg-base-200">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 py-8">
          {/* Back Button + Download */}
          <div className="flex items-center gap-3 mb-6">
            <button
              className="btn btn-ghost btn-sm gap-2"
              onClick={() => navigate("/ai-practice/history")}
            >
              <ArrowLeftIcon className="size-4" />
              Back to History
            </button>
            <button
              className="btn btn-outline btn-sm gap-2"
              onClick={() =>
                handleDownloadReport(session.feedback, {
                  topic: session.topic,
                  difficulty: session.difficulty,
                  questionCount: session.questionCount,
                  totalDuration: session.totalDuration,
                })
              }
            >
              <DownloadIcon className="size-4" />
              Download Report
            </button>
          </div>

          {/* Session Meta */}
          <div className="flex flex-wrap items-center gap-3 mb-6">
            <h1 className="text-2xl font-black">
              {session.mode === "topic"
                ? session.topic || "Topic Interview"
                : "Resume Interview"}
            </h1>
            <span
              className={`badge ${
                session.mode === "topic" ? "badge-info" : "badge-secondary"
              }`}
            >
              {session.mode === "topic" ? "Topic" : "Resume"}
            </span>
            {session.difficulty && (
              <span
                className={`badge ${
                  session.difficulty === "Easy"
                    ? "badge-success"
                    : session.difficulty === "Medium"
                    ? "badge-warning"
                    : "badge-error"
                }`}
              >
                {session.difficulty}
              </span>
            )}
          </div>

          <div className="flex flex-wrap gap-4 text-sm text-base-content/60 mb-8">
            <div className="flex items-center gap-1">
              <ClockIcon className="size-4" />
              {formatDuration(session.totalDuration)}
            </div>
            <div className="flex items-center gap-1">
              <MessageSquareIcon className="size-4" />
              {session.questionCount || 0} questions
            </div>
            <div>{formatDate(session.createdAt)}</div>
          </div>

          {/* Feedback Card */}
          {session.feedback && (
            <div className="mb-8">
              <AIFeedbackCard
                variant="practice"
                feedback={session.feedback}
                sessionMeta={{
                  mode: session.mode,
                  topic: session.topic,
                  difficulty: session.difficulty,
                  questionCount: session.questionCount,
                  totalDuration: session.totalDuration,
                }}
              />
            </div>
          )}

          {/* Conversation Transcript */}
          <div className="card bg-base-100 shadow-md border border-base-300">
            <div className="card-body">
              <h2 className="font-bold text-lg mb-4 flex items-center gap-2">
                <MessageSquareIcon className="size-5 text-primary" />
                Conversation Transcript
              </h2>
              <div className="space-y-4">
                {session.messages?.map((msg, i) => (
                  <div
                    key={i}
                    className={`flex ${
                      msg.role === "ai" ? "justify-start" : "justify-end"
                    }`}
                  >
                    <div
                      className={`flex gap-3 max-w-[80%] ${
                        msg.role === "ai" ? "flex-row" : "flex-row-reverse"
                      }`}
                    >
                      <div
                        className={`flex-shrink-0 size-8 rounded-full flex items-center justify-center ${
                          msg.role === "ai"
                            ? "bg-gradient-to-br from-primary to-secondary"
                            : "bg-primary/20"
                        }`}
                      >
                        {msg.role === "ai" ? (
                          <SparklesIcon className="size-4 text-white" />
                        ) : (
                          <span className="text-xs font-bold text-primary">
                            You
                          </span>
                        )}
                      </div>
                      <div>
                        <div className="text-xs font-semibold mb-1 text-base-content/60">
                          {msg.role === "ai" ? "Interviewer" : "You"}
                        </div>
                        <div
                          className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                            msg.role === "ai"
                              ? "bg-base-300 text-base-content"
                              : "bg-primary/20 text-base-content"
                          }`}
                        >
                          {msg.content}
                        </div>
                        {msg.timeTaken > 0 && (
                          <div className="text-xs text-base-content/40 mt-1">
                            (answered in {msg.timeTaken}s)
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════════
  // VIEW 1: History List
  // ═══════════════════════════════════════════════════════════════
  return (
    <div className="min-h-screen bg-base-200">
      <Navbar />
      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center gap-3 mb-8">
          <div className="size-10 rounded-xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
            <HistoryIcon className="size-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-black">Practice History</h1>
            <p className="text-sm text-base-content/60">
              Review your past AI practice interview sessions
            </p>
          </div>
        </div>

        {/* Score Trend Chart */}
        {!loading && history.length >= 2 && (
          <div className="card bg-base-100 shadow-md border border-base-300 mb-6">
            <div className="card-body py-4">
              <h2 className="font-bold text-sm text-base-content/70 mb-3">
                Score Trend
              </h2>
              <ResponsiveContainer width="100%" height={160}>
                <LineChart
                  data={[...history].reverse().map((s, i) => ({
                    name: `#${i + 1}`,
                    score: s.feedback?.overallScore || 0,
                    topic: s.topic || "Resume",
                  }))}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} />
                  <YAxis domain={[0, 10]} tick={{ fontSize: 10 }} />
                  <Tooltip
                    formatter={(val) => [`${val}/10`, "Score"]}
                    labelFormatter={(label, payload) =>
                      payload?.[0]?.payload?.topic || label
                    }
                  />
                  <Line
                    type="monotone"
                    dataKey="score"
                    stroke="#22C55E"
                    strokeWidth={2}
                    dot={{ fill: "#22C55E", r: 4 }}
                    activeDot={{ r: 6 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}

        {/* Topic Performance Breakdown */}
        {!loading && history.length >= 1 && (() => {
          const topicStats = history.reduce((acc, session) => {
            const key = session.topic || "Resume";
            if (!acc[key]) acc[key] = { topic: key, total: 0, count: 0 };
            acc[key].total += session.feedback?.overallScore || 0;
            acc[key].count += 1;
            return acc;
          }, {});
          const topicArray = Object.values(topicStats)
            .map((t) => ({ ...t, avg: Math.round((t.total / t.count) * 10) / 10 }))
            .sort((a, b) => b.avg - a.avg);

          return (
            <div className="card bg-base-100 shadow-md border border-base-300 mb-6">
              <div className="card-body py-4">
                <h2 className="font-bold text-sm text-base-content/70 mb-3">
                  Performance by Topic
                </h2>
                <div className="space-y-2">
                  {topicArray.map((t) => (
                    <div key={t.topic} className="flex items-center gap-3">
                      <span className="text-sm w-32 truncate font-medium">{t.topic}</span>
                      <progress
                        className={`progress flex-1 ${
                          t.avg >= 7
                            ? "progress-success"
                            : t.avg >= 4
                            ? "progress-warning"
                            : "progress-error"
                        }`}
                        value={t.avg}
                        max={10}
                      />
                      <span className="text-sm font-mono w-12 text-right">
                        {t.avg}/10
                      </span>
                      <span className="text-xs text-base-content/40 w-6">
                        {t.count}x
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          );
        })()}

        {loading ? (
          /* Loading skeleton */
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {[...Array(6)].map((_, i) => (
              <div
                key={i}
                className="card bg-base-100 shadow-md border border-base-300 animate-pulse"
              >
                <div className="card-body">
                  <div className="h-4 bg-base-300 rounded w-1/3 mb-2" />
                  <div className="h-5 bg-base-300 rounded w-2/3 mb-4" />
                  <div className="h-8 bg-base-300 rounded w-1/4" />
                </div>
              </div>
            ))}
          </div>
        ) : history.length === 0 ? (
          /* Empty state */
          <div className="text-center py-20">
            <SparklesIcon className="size-16 mx-auto mb-4 text-base-content/20" />
            <h2 className="text-xl font-bold mb-2">
              No practice sessions yet
            </h2>
            <p className="text-base-content/60 mb-6">
              Start your first AI-powered practice interview!
            </p>
            <button
              className="btn btn-primary"
              onClick={() => navigate("/ai-practice")}
            >
              Start Practicing
            </button>
          </div>
        ) : (
          <>
            {/* Grid of cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {history.map((session) => (
                <SessionHistoryCard
                  key={session._id}
                  session={session}
                  onClick={() =>
                    navigate(`/ai-practice/history/${session._id}`)
                  }
                />
              ))}
            </div>

            {/* Pagination */}
            {historyMeta.totalPages > 1 && (
              <div className="flex justify-center mt-8">
                <div className="join">
                  {[...Array(historyMeta.totalPages)].map((_, i) => (
                    <button
                      key={i}
                      className={`join-item btn btn-sm ${
                        historyMeta.page === i + 1 ? "btn-active" : ""
                      }`}
                      onClick={() => loadHistory(i + 1)}
                    >
                      {i + 1}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default AIPracticeHistoryPage;
